[package]
name = "poser"
version = "0.1.0"
authors = ["Richard Hart <richardhart92@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rstar = "0.2.0"
uuid = "0.8.2"
